services:
  postgres:
    image: postgres:16.9
    container_name: myblog-postgres
    environment:
      # В реальном приложении все креды будут вынесены в env или хранилище секретов,
      # здесь проставлены дефолтные значения только для упрощения локальной сборки и ревью
      POSTGRES_DB: ${POSTGRES_DB:-myblog}
      POSTGRES_USER: ${POSTGRES_USER:-myblog_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myblog-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myblog-app
    ports:
      - "${APP_PORT:-18080}:8080"
    depends_on:
      - postgres
    environment:
      # В реальном приложении все креды будут вынесены в env или хранилище секретов,
      # здесь проставлены дефолтные значения только для упрощения локальной сборки и ревью
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-myblog}
      - DB_USER=${POSTGRES_USER:-myblog_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - uploads_data:/app/uploads
    networks:
      - myblog-network

volumes:
  postgres_data:
  uploads_data:

networks:
  myblog-network:
    driver: bridge