DROP TABLE IF EXISTS post_tags;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS post;

CREATE TABLE IF NOT EXISTS post (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  filename VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tag (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS comment (
  id BIGSERIAL PRIMARY KEY,
  post_id BIGINT,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_comment_post
      FOREIGN KEY (post_id)
      REFERENCES post(id)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS post_tags (
  id BIGSERIAL PRIMARY KEY,
  post_id BIGINT,
  tag_id BIGINT,
  UNIQUE (post_id, tag_id),
  CONSTRAINT fk_post_tags_post
      FOREIGN KEY (post_id)
      REFERENCES post(id)
      ON DELETE CASCADE,
  CONSTRAINT fk_post_tags_tag
      FOREIGN KEY (tag_id)
      REFERENCES tag(id)
      ON DELETE CASCADE
);